### ISSUE TITLE
False / Positive  dans la règle bzn  is_pos pour les données agrégées 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaDraft#37]
Voilà l'exemple à traiter :

![bug_bzn_is_pos](https://user-images.githubusercontent.com/22026724/34666573-54b3e844-f465-11e7-9d33-e779f31d4d53.png)

Ici  BZN est très petit (10^-12) et on valide le fait que la donnée est positive. 

Ceci est due au calcul fait lors de l'agrégation pour créer la donnée. 

Pour ne plus avoir ça, il faudrait modifier le fichier "agg_validate.yml "

à ce niveau

AVANT 
```yaml 

- expr: CTY > 0
  name: CTY_IS_POS
- expr: CTA > 0
  name: CTA_IS_POS
- expr: BZN > 0
  name: BZN_IS_POS

```

APRES 

```yaml 

- expr: CTY > 0
  name: CTY_IS_POS
- expr: CTA > 0
  name: CTA_IS_POS
- expr: BZN > 0.001
  name: BZN_IS_POS

```
