### ISSUE TITLE
more complexity in `cty_rules.yaml`

### ISSUE THREAD

**Issue by davidgohel** [rte-antares-rpackage/antaDraft#9]
Pouvoir dans `cty_rules.yaml` enlever (pour une DateTime) la valeur du CTY validé d'un pays donné pour calculer le BZN d'un pays donné (peut être différent du précédent)

**Comment by davidgohel** [comment]
```
UK:
  CTY:
    - GB
    - !NIE
  CTA:
    - GB
  BZN:
    - GB
```

**Comment by jalazawa** [comment]
c'est plutôt ça 

```
UK:
  CTY:
    - GB
    - CTA!NIE (si CTA!NIE a été validé)
  CTA:
    - GB
  BZN:
    - GB
```

**Comment by jalazawa** [comment]
autre exemple 

si les deux CTY DE et AT sont valides

LUXEMBOURG:
  CTY:
    - LU
  CTA:
    - LU
  BZN:
    - DE_AT_LU
    - !CTY|DE
    - !CTY|AT

**Comment by FabiolaAravena** [comment]
Exemple pour l'Autriche, si les deux CTY DE et LU sont valides : 

AUSTRIA:
  CTY:
    - AT
  CTA:
    - AT
  BZN:
    - DE_AT_LU
    - !CTY|DE
    - !CTY|LU

**Comment by FabiolaAravena** [comment]
Cas de l'Allemagne si les deux CTY AT et LU sont valides :

GERMANY:
  CTY:
    - DE
  CTA:
    - DE_TenneT_GER
    - DE_TransnetBW
    - DE_Amprion
    - DE_50HzT
  BZN:
    - DE_AT_LU
    - !CTY|AT
    - !CTY|LU

**Comment by jalazawa** [comment]
nouvelles règles de comparaison pour NIE si CTY|IE est valide

```

NORTH_IRELAND:
  CTY:
    - NIE
  CTA:
    - NIE
  BZN:
    - IE_SEM
   - !CTY|IE

```
